### Ejercicio 3 - Traductor

diccionario = {
    "casa": "house",
    "perro": "dog",
    "gato": "cat",
    "sol": "sun",
    "luna": "moon",
    "agua": "water",
    "comida": "food",
    "libro": "book",
    "mesa": "table",
    "silla": "chair",
    "computadora": "computer",
    "telefono": "phone",
    "coche": "car",
    "calle": "street",
    "ciudad": "city",
    "país": "country",
    "gente": "people",
    "amigo": "friend",
    "familia": "family",
    "trabajo": "work",
    "escuela": "school",
    "universidad": "university",
    "mañana": "morning",
    "tarde": "afternoon",
    "noche": "night",
    "siempre": "always",
    "nunca": "never",
    "a veces": "sometimes",
    "rápido": "fast",
    "lento": "slow",
    "grande": "big",
    "pequeño": "small",
    "feliz": "happy",
    "triste": "sad",
    "caliente": "hot",
    "frío": "cold",
    "rojo": "red",
    "azul": "blue",
    "verde": "green",
    "amarillo": "yellow",
    "blanco": "white",
    "negro": "black",
    "cinco": "five",
    "diez": "ten",
    "cien": "hundred",
    "uno": "one",
    "dos": "two",
    "tres": "three",
    "cuatro": "four",
    "seis": "six",
    "siete": "seven",
    "ocho": "eight",
    "nueve": "nine",
    "comer": "to eat",
    "beber": "to drink",
    "dormir": "to sleep",
    "correr": "to run",
    "caminar": "to walk",
    "hablar": "to talk",
    "escribir": "to write",
    "leer": "to read",
    "ver": "to see",
    "escuchar": "to listen",
    "abrir": "to open",
    "cerrar": "to close",
    "empezar": "to start",
    "terminar": "to finish",
    "ayudar": "to help",
    "buscar": "to look for",
    "encontrar": "to find",
    "dar": "to give",
    "tomar": "to take",
    "venir": "to come",
    "ir": "to go",
    "hoy": "today",
    "ayer": "yesterday",
    "mañana (día)": "tomorrow",
    "problema": "problem",
    "solución": "solution",
    "historia": "history",
    "arte": "art",
    "ciencia": "science",
    "música": "music",
    "película": "movie",
    "juego": "game",
    "dinero": "money",
    "tiempo": "time",
    "mundo": "world",
    "vida": "life",
    "muerte": "death",
    "esperanza": "hope",
    "sueño": "dream",
    "verdad": "truth",
    "mentira": "lie",
    "fácil": "easy",
    "difícil": "difficult",
    "fuerte": "strong",
    "débil": "weak",
    "viaje": "trip",
    "puerta": "door",
    "ventana": "window","perro": "dog",
    "gato": "cat",
    "casa": "house",
    "pequeña": "small",
    "pequeño": "small",
    "comer": "to eat",
    "comida": "food",
    "caliente": "hot",
    "beber": "to drink",
    "agua": "water",
    "coche": "car",
    "rojo": "red",
    "grande": "big",
    "azul": "blue",
    "libro": "book",
    "ciencia": "science",
    "tarde": "afternoon",
    "tres": "three",
    "cinco": "five",
    "ocho": "eight",
    "solución": "solution",
    "fácil": "easy",
    "el": "the",
    "la": "the",
    "un": "a",
    "una": "a",
    "y": "and",
    "en": "in",
    "pero": "but",
    "yo": "I",
    "ella": "she",
    "quiero": "want",
    "duermen": "sleep", 
    "es": "is",         
    "son": "are",       
    "empieza": "starts", 
    "a": "to",          
    "leer": "read",
    "sobre": "about",
    "busco": "look for",
    "ocho": "eight"
}

def traduccion(frase, diccionario):
    palabras = frase.split()
    nueva_frase = ""
    for palabra in palabras:
        if palabra in diccionario:
            nueva_frase += diccionario[palabra] + " "
        else:
            nueva_frase += palabra + " "
    return nueva_frase

def start():
    frase = "Me compré un libro sobre ciencia"
    print(traduccion(frase,diccionario))
            

start()

